version: '3.1'
services:
    screenie-mongo:
        ports:
            - "27017:27017"
        image: "mongo:3"
        healthcheck:
            test: ["CMD", "nc", "-zvv", "localhost", "27017"]
            interval: 1m30s
            timeout: 10s
            retries: 3
        restart: on-failure